config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/give', to: 'pages#give'
  get '/receive', to: 'pages#receive'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.  # Documentation Comment
  def full_title(page_title = '')                # Method def, optional arg
    base_title = "KADOSILANG"                     # Variable assignment
    if page_title.empty?                         # Booloean test
      base_title                                 # Implicit return
    else
      page_title + " | " + base_title            # String concatenation
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer id="contact" class="bg-dark text-white">
  <div class="container">
    <div class="row">
      <div class="text-left text-sm-center table-center">
        <h4><b>Informasi Kontak</b></h4>
        <table width="25%">
          <tr>
            <td>Email</td>
            <td>:</td>
            <td>kontak.kadosilang@gmail.com</td>
          </tr>
          <tr>
            <td>WhatsApp</td>
            <td>:</td>
            <td>+62-821-3793-5611</td>
          </tr>
          <tr>
            <td>Instagram</td>
            <td>:</td>
            <td><a href="http://www.instagram.com/kadosilang/" target="_blank">kadosilang</a></td>
          </tr>
        </table>
      </div>
      <p>© 2019 KADOSILANG</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <%= link_to "KADOSILANG", root_path, id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Beranda", root_path %></li>
        <li><%= link_to "Tentang", root_path(:anchor => "about") %></li>
        <li><%= link_to "Layanan", root_path(:anchor => "service") %></li>
        <li><a href="#contact">Kontak</a></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Bootstrap CSS -->
    <%# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> %>
    
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Tangerine">
    <style>
      body {
        font-family: 'Linotte', Serif;
        /* font-size: 48px; */
      }
    </style>
  </head>
  <body data-spy="scroll">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <%# <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> %>
  </body>
</html>

app/views/pages/_about.html.erb
<section id="about">
  <br>
  <hr>
  <div class="col-lg-12 mx-auto" align="justify">
    <h2 class="text-blue b">Tentang Kadosilang</h2>
    <div class="mt-5 mb-4 pb-3">
      <p>
        Kadosilang adalah sebuah gerakan yang berupaya mengajak
        masyarakat untuk saling memberikan barang yang sudah tidak
        terpakai lagi kepada orang lain yang membutuhkan. Kami
        percaya bahwa kasih sayang dan perdamaian akan tercipta ketika
        manusia saling berbagi satu sama lain.
      </p>
      <br>
    </div>
  </div>
  <div class="col-lg-6 mx-auto" align="center">
    <h3 class="text-blue b">VISI</h3>
    <br>
    <div class="mt-5 mb-4 pb-3">
      <p>Menumbuhkan budaya saling memberi demi terciptanya 
      <br>masyarakat yang damai serta lingkungan yang lestari.</p>
      <br>
    </div>
  </div>
  <div class="col-lg-6 mx-auto" align="center">
    <h3 class="text-blue b">MISI</h3>
    <br>
    <div class="mt-5 mb-4 pb-3">
      <p>Menyediakan komunitas dan platform online 
      <br>untuk saling memberi satu sama lain.</p>
    </div>
  </div>
</section>

app/views/pages/_service.html.erb
<section id="service">
  <br>
  <hr>
  <div class="col-lg-12 mx-auto" align="justify">
    <h2 class="text-blue b">Layanan Kadosilang</h2>
    <div class="mt-5 mb-4 pb-3">
    </div>
  </div>
  <div class="col-lg-6 mx-auto" align="center">
    <h3 class="text-blue b">GIVE</h3>
    <br>
    <div class="center mt-5 mb-4 pb-3">
      <p>Kamu bisa memberikan barangmu yang tidak terpakai 
      <br>kepada orang yang membutuhkan.</p>
    </div>
  </div>
  <div class="col-lg-6 mx-auto" align="center">
    <h3 class="text-blue b">RECEIVE</h3>
    <br>
    <div class="center mt-5 mb-4 pb-3">
      <p>Kamu bisa mendapatkan barang orang lain
      <br>yang sudah tidak terpakai.</p>
      <br><br><br><br><br><br>
    </div>
  </div>
</section>

app/views/pages/give.html.erb
<h1>Give Page</h1>
<div class="col-lg-1 mx-auto">
</div>
<div class="col-lg-4 mx-auto">
  <h2>Umumkan barang milikmu!</h2>
  <ol>
    <li>Siapkan foto barang yang akan kamu diberikan.</li>
    <li>Isi form pada
      <a href="https://bit.ly/GiveKX" target="_blank">tautan ini.</a>
    </li>
    <li>Tunggu seseorang mengambil barang kamu. <br>*Kami akan mengontak kamu apabila ada orang yang ingin mengambilnya.*</li>
    <li>Terima kasih sudah menggunakan layanan kami!</li>
  </ol>
</div>
<div class="col-lg-2 mx-auto">
</div>
<div class="col-lg-4 mx-auto">
  <h2>Lihat yang orang butuhkan!</h2>
  <ol>
    <li>Lihat barang yang orang butuhkan
      <a href="https://bit.ly/DemandedKX" target="_blank">di sini.</a>
    </li>
    <li>Download foto barang yang kamu pilih untuk kamu berikan.</li>
    <li>Hubungi kami via aplikasi WhatsApp dengan klik tombol  
      <%= link_to image_tag("WA.png", alt: "WA", ), href="https://api.whatsapp.com/send?phone=6282137935611&text=Halo%20Kadosilang!%20Saya%20bersedia%20memberikan%20barang%20di%20bawah%20ini%20untuk%20orang%20yang%20membutuhkan!%0A%0AMohon%20konfirmasinya!%20Terima%20kasih!%0A%0A[Upload%20foto%20di%20bawah]&source=&data=", target: :_blank %>
      atau hubungi kami di no +62-821-3793-5611.
    </li>
    <li>Terima kasih sudah menggunakan layanan kami!</li>
  </ol>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/pages/home.html.erb
<section id="home">
  <div class="center bg">
    <br><br><br><br><br>
    <h1>Selamat datang di</h1>
    <br>
    <%= image_tag("logo.png", alt: "Meja", width: 250)%>
    <br>
    <p class="tagline">Free gift for everyone</p><br>
    <table align="center"> 
      <tr>
        <td><%= link_to image_tag("startGiving.png"), give_path %></td>
        <td class="option"></td>
        <td><%= link_to image_tag("startReceiving.png"), receive_path %></td>
      </tr>
    </table>
    <br><br><br><br><br><br><br><br><br><br><br>
  </div>
  <div>
    <%= render 'pages/about' %>
    <%= render 'pages/service' %>
  </div>
  <br>
</section>

app/views/pages/receive.html.erb
<h1>Receive Page</h1>
<div class="col-lg-1 mx-auto">
</div>
<div class="col-lg-4 mx-auto">
  <h2>Umumkan barang yang kamu cari!</h2>
  <ol>
    <li>Siapkan foto barang yang ingin kamu cari.</li>
    <li>Isi form pada
      <a href="https://bit.ly/ReceiveKX" target="_blank">tautan ini.</a>
    </li>
    <li>Tunggu seseorang memberikan barang tersebut. 
    <br>*Kami akan mengontak kamu apabila ada orang yang ingin memberikannya.*</li>
    <li>Terima kasih sudah menggunakan layanan kami!</li>
  </ol>
</div>
<div class="col-lg-2 mx-auto">
</div>
<div class="col-lg-4 mx-auto">
  <h2>Lihat yang telah tersedia!</h2>
  <ol>
    <li>Lihat barang yang orang berikan
      <a href="https://bit.ly/AvailableKX" target="_blank">disini.</a>
    </li>
    <li>Download foto barang yang kamu pilih untuk kamu ambil.</li>
    <li>Hubungi kami via aplikasi WhatsApp dengan klik tombol  
      <%= link_to image_tag("WA.png", alt: "WA", ), href="https://api.whatsapp.com/send?phone=6282137935611&text=Halo%20Kadosilang!%20Saya%20bersedia%20memberikan%20barang%20di%20bawah%20ini%20untuk%20orang%20yang%20membutuhkan!%0A%0AMohon%20konfirmasinya!%20Terima%20kasih!%0A%0A[Upload%20foto%20di%20bawah]&source=&data=", target: :_blank %>
      atau hubungi kami di no +62-821-3793-5611.
    </li>
    <li>Terima kasih sudah menggunakan layanan kami!</li>
  </ol>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>